Add citation info
hpsim/OGL pull request #133
Opened 2024-06-17 14:57 UTC by chihta-wang

1. Update citation info in README
2. Add a file for citation

2024-06-17 15:53 UTC, greole requested changes

2024-06-17 15:53 UTC, greole commented on CITATION.cff
> +  journal: " Meccanica"
```suggestion
  journal: "Meccanica"
```

2024-06-17 15:53 UTC, greole commented on CITATION.cff
> +    given-names: "Hartwig"
```suggestion
- name "The OGL authors"
```

2024-06-17 15:53 UTC, greole commented on README.md
> +}
Please move this above the Ginkgo paper

2024-06-18 11:39 UTC, chihta-wang commented on CITATION.cff
> +  journal: " Meccanica"
Done

2024-06-18 11:40 UTC, chihta-wang commented on CITATION.cff
> +    given-names: "Hartwig"
Update as requested

2024-06-18 11:40 UTC, chihta-wang commented on README.md
> +}
Done

2024-06-18 12:10 UTC, greole approved these changes

2024-06-18 12:20 UTC, merged