Persistent device id guard
hpsim/OGL pull request #90
Opened 2023-08-01 08:57 UTC by greole

This PR adds a persistent wrapper to `gko::device_id_guard` to avoid unnecessary transferring data between GPUs in multi GPU runs. Additional changes are:

- renaming of DevicePersistent sub-folder to be more consistent 
- fix of #includes paths

2023-08-01 17:59 UTC, zbinkz commented on README.md
>  additionally, the following preconditioner are available
```suggestion
additionally, the following preconditioners are available
```

2023-08-01 18:00 UTC, zbinkz commented on README.md
> +### Supported Matrix Format (Experimental)
```suggestion
### Supported Matrix Formats (Experimental)
```

2023-08-01 18:02 UTC, zbinkz commented on README.md
> +Currently only basic cyclic boundary conditions are supported. Block-coupled matrices are not supported.
```suggestion
Currently, only basic cyclic boundary conditions are supported. Block-coupled matrices are not supported.
```

2023-08-01 18:04 UTC, zbinkz commented on README.md
>  This repo contains mainly proof of concept work. This might change in future if we can acquire some funding and do some proper redesigning. Until then feel free to play around and contact me if anyth
```suggestion
This repository contains mainly proof of concept work. This might change in the future should we receive funding to that effect, and redesign properly. Until then feel free to play around and contact me if anything doesn't work.
```

2023-08-01 18:04 UTC, zbinkz reviewed
Minor typos and English style corrections. Otherwise, LGTM!

2023-08-01 18:22 UTC, zbinkz commented on CMakeLists.txt
> +#Configuration options
```suggestion
# Configuration options
```
Having the space between # and the comment is preferred programming practice. Space savings are irrelevant here, and why make a comment look like a compiler directive?

2023-08-01 18:26 UTC, zbinkz commented on CMakeLists.txt
> +#If ginkgo wasn't found so far look for the third_party installation
```suggestion
# If ginkgo is not found at this point, look for the third_party installation
```

2023-08-01 18:27 UTC, zbinkz commented on CMakeLists.txt
> +#To interface with ginkgo at least C++ 14 is needed
```suggestion
# C++ 14 standard or later is required to interface with ginkgo 
```

2023-08-01 18:28 UTC, zbinkz commented on CMakeLists.txt
> +#actually produced, in order to force version.cmake to always be re - run before
```suggestion
# actually produced, in order to always force re-run version.cmake before
```

2023-08-01 18:33 UTC, zbinkz commented on README.md
>  A wrapper for [ginkgo](https://github.com/ginkgo-project/ginkgo) solvers and preconditioners to provide GPGPU capabilities to OpenFOAM.
```suggestion
OGL is a wrapper for [ginkgo](https://github.com/ginkgo-project/ginkgo) solvers and preconditioners to provide GPGPU capabilities to OpenFOAM.
```

2023-08-01 18:36 UTC, zbinkz requested changes
Only some minor stylistic changes and typo corrections. I am really puzzled about removing the space between the comment symbol # and the rest of the comment in CMakeList.txt. This is generally considered bad programming style. What do we gain from implementing it?

2023-08-02 05:52 UTC, greole commented on CMakeLists.txt
> +#Configuration options
Thanks, I accidentally ran `clang-format` on that file, which seems to remove the space here.

2023-08-02 23:59 UTC, zbinkz approved these changes
LGTM

2023-08-03 08:24 UTC, greole commented
Thanks for the review @zbinkz. The deleted ws came from a problem with clang-format.

2023-08-03 08:24 UTC, merged